export const LOAD_DREAM_TYPE_SUCCESS = "LOAD_DREAM_TYPE_SUCCESS";
export const LOAD_DREAMERS_TYPE_SUCCESS = "LOAD_DREAMERS_TYPE_SUCCESS";

export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_LOG_OUT_SUCCESS = "USER_TOKEN_LOG_OUT_SUCCESS";
